apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{.function_name}}
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "{{.autoscaler_type}}.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "{{.metric}}"
        autoscaling.knative.dev/min-scale: "{{.min_scale}}"
        autoscaling.knative.dev/max-scale: "{{.max_scale}}"
        autoscaling.knative.dev/scale-down-delay: "{{.scale_down_delay}}"
        autoscaling.knative.dev/window: "{{.window}}"
        {{if .target}}autoscaling.knative.dev/target: "{{.target}}"{{end}}
        {{if .target_utilization_percentage}}autoscaling.knative.dev/target-utilization-percentage: "{{.target_utilization_percentage}}"{{end}}
    spec:
      containers:
        - image: docker.io/notnew77/{{.function_type}}:latest
          ports:
          - containerPort: 8080
            {{if eq .protocol "grpc"}}name: "h2c"{{end}}
          resources:
            requests:
              cpu: {{.min_cpu}}
              memory: {{.min_memory}}
            limits:
              cpu: {{.max_cpu}}
              memory: {{.max_memory}}
          env:
          - name: FUNCTION_NAME
            value: {{.function_name}}
          - name: SUCCESSORS
            value: {{.successors}}