
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f3
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/notnew77/cache:latest
          ports:
          - containerPort: 8080
          env:
          - name: FUNCTION_NAME
            value: "f3"
          - name: SUCCESSORS
            value: ""