apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cache
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/notnew77/cache:latest
          ports:
          - containerPort: 8080